-- ============================================================
-- AUDIO ASSETS
-- Centraliza todos os áudios utilizados pelo Salmorize.
-- ============================================================

create table public.audio_assets (
  id bigint generated by default as identity primary key,

  -- Tipo/contexto do áudio:
  -- psalm_title, verse, onboarding, explanation, etc.
  type text not null,

  -- Relação opcional com o Salmo
  psalm_id bigint references public.psalms(id) on delete cascade,

  -- Relação opcional com um verso
  verse_id bigint references public.verses(id) on delete cascade,

  -- Idioma do áudio
  language text not null default 'pt-BR',

  -- Caminho relativo dentro do bucket
  storage_path text not null,

  created_at timestamptz not null default now()
);

-- ============================================================
-- ÍNDICES
-- ============================================================

create index audio_assets_psalm_id_idx
  on public.audio_assets(psalm_id);

create index audio_assets_verse_id_idx
  on public.audio_assets(verse_id);

create index audio_assets_type_idx
  on public.audio_assets(type);